steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/attire-app:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/attire-app:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Persistent Volume'
    args: ['apply', '-f', 'persistent-volume.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=attire-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Persistent Volume Claim'
    args: ['apply', '-f', 'persistent-volume-claim.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=attire-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Create Deployment'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=attire-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Update Deployment Image'
    args: ['set', 'image', 'deployment.apps/attire-app-deployment', 'attire-app=gcr.io/$PROJECT_ID/attire-app:$BUILD_ID']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=attire-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Service'
    args: ['apply', '-f', 'service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=attire-cluster'

images:
  - 'gcr.io/$PROJECT_ID/attire-app:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
