apiVersion: v1
kind: PersistentVolume
metadata:
  name: attire-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: attire-disk
    fsType: ext4


