apiVersion: v1
kind: PersistentVolume
metadata:
  name: attire-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: your-disk-name
    fsType: ext4
